### ISSUE TITLE
 Block synchronization on Nile stops at block 10328108 

### ISSUE THREAD

**Issue by oikos1** [opentron/opentron#57] opened 2021-01-21 02:30 UTC
Seems like block synchronization stops at block 10328108. I am starting the program with:

```cargo run -- --config etc/conf.nile.toml ```

![errot](https://user-images.githubusercontent.com/59787133/105271998-e61b2180-5b6e-11eb-87e1-20c29d95c0ae.png)

**Comment by andelf** [comment] 2021-02-05 10:55
TODO: impl a skip list of blocks in config file.

**Comment by andelf** [comment] 2021-03-15 07:47
Update 2021/03/15

Since this is testnet-only and is caused by java-tron bug, mark it as `wontfix`.

**Closed** 2021-03-26 17:26 UTC
Labels: invalid-protobuf, testnet-nile, wontfix
